### ISSUE TITLE
Set cursor over class entry to pointer instead of regular cursor

### ISSUE THREAD

**Issue by jkingsman** [COEN174/MainProject#41]

**Comment by jkingsman** [comment]
Should be pretty easy to solve with a 

``` css
.list-group-item {
    cursor: pointer;
}
```
